### ISSUE TITLE
Breaks MultipartRequest uploads

### ISSUE THREAD

**Issue by KirioXX** [Instabug/Instabug-Dart-http-Adapter#11]
We tried to use the HTTP adapter to as a client for our [supabase](https://supabase.com/docs/reference/dart) instance.

But when we try to upload files we get this error: 
"type 'MultipartRequest' is not a subtype of type 'Request' in type cast"

We set up the supabase client like this:
```dart
  // Supabase
  final client = InstabugHttpClient();
  await Supabase.initialize(
    url: dotenv.env['SUPABASE_URL']!,
    anonKey: dotenv.env['SUPABASE_ANON_KEY']!,
    httpClient: client,
  );
```

The function we use in supabase is the `from.upload`: 
https://supabase.com/docs/reference/dart/storage-from-upload

This is the part in supabase that does the multipart upload:
https://github.com/supabase-community/storage-dart/blob/70d051fa569b887eb97c8f415b5177aebb6d0e48/lib/src/fetch.dart#L72-L102

Is there something that we could have missed on the setup?
Thank you.

**Comment by DavidMina96** [comment]
Hi @KirioXX, 

Thanks a lot for reporting this. We'll look into it and get back to you.

**Comment by DavidMina96** [comment]
@KirioXX A new version of the package v2.3.0 is now released, which adds support for MultipartRequest. 

Please update to this version and feel free to let us know if you still have any inquiries or issues at all.

**Comment by KirioXX** [comment]
Awesome! Thank you very much @DavidMina96 🙇‍♂️
