### ISSUE TITLE
Allow InstabugHttpClient to be composable with other http clients

### ISSUE THREAD

**Issue by dustin-graham** [Instabug/Instabug-Dart-http-Adapter#15]
Our app integrates with several other services which provide custom http client implementations. In order to work with all of them we need a sensible way to compose the various clients together. One common way to do this is to provide an optional "inner client" that we can provide to which all network requests are forwarded. This would allow, for example, an application to integrate with DataDog in addition to Instabug.

**Comment by a7medev** [comment]
Hi @dustin-graham! Thanks a lot for the suggestion and I think you have a very valid point.
I see you've already created a PR for adding that feature which we really appreciate 🙏🏼, I'll check the PR so we can get this feature out.

**Comment by dustin-graham** [comment]
Thanks. Tomorrow I’ll make a second pr for the content filtering feature we
added. Basically it’s a delegate class you can implement which lets you
strip anything out of request and response headers and request and response
bodies before they are sent to Instabug

**Comment by a7medev** [comment]
We've merged #16 which fixes this issue into `dev` and it will be included in the next release.
