### ISSUE TITLE
Update HTTP package to http 1.2.0

### ISSUE THREAD

**Issue by joshuadeguzman** [Instabug/Instabug-Dart-http-Adapter#19]
### Description

- This package depends on an old version of the http package
- To make it work with our projects, and potentially other users, this package should be using http package as well
- Based on the changelog, there aren't breaking features migrating from v13.x to v1.2.0
- See changelog: https://pub.dev/packages/http

**Comment by a7medev** [comment]
I've merged #20 into `dev` and it will be included in the next release. Thanks once again for reporting this issue and the PR.
