### ISSUE TITLE
Reason why SEND is not logged

### ISSUE THREAD

**Issue by golane-august** [Instabug/Instabug-Dart-http-Adapter#7]
Hi maintainers,
is there a reason why the SEND request is not logged? 
[  Future<http.StreamedResponse> send(http.BaseRequest request)](https://github.com/Instabug/Instabug-Dart-http-Adapter/blob/f1c5fb97ee58f5e4e9caac18f367dd2dce2f53b3/lib/instabug_http_client.dart#L99)

If this would be a valid addition, I will open a PR. Thx

**Comment by AliAbdelfattah** [comment]
Thank you @golane-august for reporting this, we're looking into the issue and your PR as well. We'll keep you updated.
